### ISSUE TITLE
How can I make custom factory single?

### ISSUE THREAD

**Issue by xkyii** [ssannandeji/Zenject-2019#280]
Hi, here is code:
```
class CustomFooFactory : IFactory<string, Foo>
{
	public CustomFooFactory() {
		Debug.Log("CustomFooFactory ctor");
	}
	public Foo Create(string value)
	{
		return new Foo(value);
	}
}

interface IFoo
{
	string Value{get;}
}

class IFooFactory : Factory<string, IFoo>
{
}

class Foo : IFoo
{
	public Foo(string value)
	{
		Value = value;
	}

	public string Value { get; private set; }
	
	public class Factory : Factory<string, Foo>
	{
	}
}

Container.BindFactory<string, Foo, Foo.Factory>().FromFactory<CustomFooFactory>().NonLazy();
var factory = Container.Resolve<Foo.Factory> ();
factory.Create ("1");
factory.Create ("2");
factory.Create ("3");
factory.Create ("4");
factory.Create ("5");
```
Every time create Foo by factory, will create new CustomFooFactory too, how can I make CustomFooFactory single?

**Comment by svermeulen** [comment]
You're right, the factory should be created once and cached, just like how other factories work.

I've fixed this with the most recent commit on the master branch, let me know if that doesn't work

**Comment by master-lincoln** [comment]
That doesn't work ;)
You forgot to declare the caching variable `_factory`. Thus the current state won't compile...

**Comment by svermeulen** [comment]
Curse my programming hubris!  Thanks.  Fixed now
