### ISSUE TITLE
Error after upgrade (5.4.0->7.1.0) with off-main-thread instantiation

### ISSUE THREAD

**Issue by jhamell** [ssannandeji/Zenject-2019#518]
Hello,

We currently use UdpClient.BeginReceive to fetch XML messages over UDP, parse into XmlNode, use Zenject factories to create local instances, and then enqueue the objects for reading by the main dispatch thread.

After upgrading Zenject (full disclosure: Unity upgraded at same time from 2017->2018), I'm now seeing an exception raised during the use of the Zenject factory.  
```
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
UnityEngine.Profiling.Profiler:get_enabled()
Zenject.ProfileBlock:Start(String, Object) (at Assets/Plugins/Zenject/Source/Util/ProfileBlock.cs:89)
Zenject.DiContainer:InstantiateExplicit(Type, Boolean, InjectArgs) (at Assets/Plugins/Zenject/Source/Main/DiContainer.cs:3100)
Zenject.TransientProvider:GetAllInstancesWithInjectSplit(InjectContext, List`1, Action&) (at Assets/Plugins/Zenject/Source/Providers/TransientProvider.cs:65)
Zenject.IProviderExtensions:GetAllInstances(IProvider, InjectContext, List`1) (at Assets/Plugins/Zenject/Source/Providers/IProviderExtensions.cs:28)
Zenject.IProviderExtensions:GetInstance(IProvider, InjectContext, List`1) (at Assets/Plugins/Zenject/Source/Providers/IProviderExtensions.cs:71)
Zenject.PlaceholderFactoryBase`1:CreateInternal(List`1) (at Assets/Plugins/Zenject/Source/Factories/PlaceholderFactoryBase.cs:32)
```

Since I'm debugging through the editor, the following is being called within our off-main-thread UDP read:
```
#if UNITY_EDITOR
            using (ProfileBlock.Start("Zenject.Instantiate({0})", concreteType))
#endif
```
which results in:
```
            if (!Profiler.enabled)
            {
                return null;
            }
```

Should we not be using this mechanism within Async processing?

Thanks,
Josh

**Comment by svermeulen** [comment]
Sounds like you need https://github.com/svermeulen/Zenject/pull/492 to be merged.  There's a multi-threading issue with ProfileBlock

**Comment by jhamell** [comment]
Thank you for the response.

**Comment by svermeulen** [comment]
Ok I believe I've addressed all the multi-threading problems

**Comment by jhamell** [comment]
Thanks for looking into this.  I applied the package 7.2.0, but am still seeing the errors:
``UnityEngine.UnityException: get_enabled can only be called from the main thread.``.  This applies to the stack trace above, Profiler.Enabled.  Currently using Unity 2018.2.6f1.  

We/I can patch locally, which is fine, but this behavior is contrary to what I thought I understood.

**Comment by svermeulen** [comment]
Yeah, I should have mentioned I still haven't made a release with those fixes yet.  `7.3.0` will have the fix.  In the meantime, you could install directly from source though
